#!/bin/bash
set -euo pipefail

mkdir -p output

INPUT="asm_examples/single_register_mov.asm"
OUTPUT="output/single_register_mov.asm"

echo "Building ${INPUT}..."

nasm ${INPUT}

echo "Successfully built."

echo "Decoding built machine code."

# Drop the .asm extension from input to get the machine code file generated by NASM
zig run src/main.zig -- --input-file ${INPUT%????} --output-file ${OUTPUT}

echo "Decoded machine code to assembly. Output destination: ${OUTPUT}"

echo "Checking diff INPUT/OUTPUT....."

diff $INPUT $OUTPUT

echo "✅ Valid decoding "
