#!/bin/bash
set -euo pipefail

mkdir -p output

INPUT="asm_examples/more_movs.asm"
OUTPUT="output/more_movs.asm"

echo "Building ${INPUT}..."

nasm ${INPUT}

echo "Successfully built."

echo "Decoding built machine code."

# Drop the .asm extension from input to get the machine code file generated by NASM
zig run src/main.zig -- --input-file ${INPUT%????} --output-file ${OUTPUT}

echo "Decoded machine code to assembly. Output destination: ${OUTPUT}"

# We are going to compile the output asm back to machine code and diff that.
# We need to do this because immediates are unsigned. So for example, the following
# two assembly instructions produce the same machine code. We have no way of knowing
# which instruction was the source for the code.
# mov cx, -12
# mov cx, 244
nasm ${OUTPUT}

echo "Checking diff INPUT/OUTPUT....."

diff ${INPUT%????} ${OUTPUT%????}

echo "✅ Valid decoding "
